name: Legit GitHub Action
run-name: Legit action by ${{ github.actor }} triggered by ${{ github.event_name }}
on: [push]

jobs:
  Legit-Action-Run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legit action run the uses a secret"
      - run: echo ${{secrets.TEST}} | base64
